name: Scheduled Netlify Deployment

on:
  push:
    branches:
      - master        # Trigger on push to master
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch:
    inputs:
      deployment_reason:
        description: 'Reason for deployment'
        required: false
        default: 'Manual trigger'
      target_env:
        description: 'Target environment (e.g., dev/staging/prod)'
        required: false
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Verify Angular CLI installation
        run: |
          echo "Checking Angular CLI version..."
          npx ng version

      - name: Build Angular project
        run: npx ng build --configuration=production

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./dist/live-posts"
          production-branch: "master"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Log deployment info
        run: |
          echo "🚀 Deployment Info:"
          echo "Reason: ${{ github.event.inputs.deployment_reason }}"
          echo "Target Environment: ${{ github.event.inputs.target_env }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
